#!/usr/local/bin/zsh

# ZSHENV GIT
#
#

# Following is provided via hub (https://github.com/github/hub) and
# wraps git automatically.
eval "$(hub alias -s)"

# Aliases
alias gpr="git pull --rebase -v"
