#!/usr/local/bin/zsh

# ZSHENV Docker
#
#

# general docker commands
alias di="docker images"
alias dps="docker ps"
alias dl="docker logs"
alias dlf="docker logs -f"
alias drm="docker rm"
alias drmi="docker rmi"

# docker-compose shortcuts
alias dc="docker-compose"
alias dcu="docker-compose up"
alias dcud="docker-compose up -d"
alias dcd="docker-compose down"

# Run bash in docker container
docker_exec_helper() {
    docker exec -it $1 bash
}
alias dex=docker_exec_helper

# Kill all running containers.
alias dockerkillall='docker kill $(docker ps -q)'

# Delete all stopped containers.
alias dockercleanc='printf "\n>>> Deleting stopped containers\n\n" && docker rm $(docker ps -a -q)'

# Delete all untagged images.
alias dockercleani='printf "\n>>> Deleting untagged images\n\n" && docker rmi $(docker images -q -f dangling=true)'

# Delete all stopped containers and untagged images.
alias dockerclean='dockercleanc || true && dockercleani'

# Delete all tangling volumes
alias dockervolclean='printf "\n>>> Deleting untagged volumes\n\n" && docker volume rm $(docker volume ls -qf dangling=true)'

# Delete all downloaded images
alias dockerimgclean='for image in `docker images -q` ; do docker rmi $image ; done'
