#!/usr/local/bin/zsh

# ZSHENV Docker
#
#

# general docker commands
alias doci="docker images"
alias docps="docker ps"

# Run bash in docker container
docker_exec_helper() {
    docker exec -it $1 bash
}
alias docex=docker_exec_helper

# Show docker logs
alias docl="docker logs"
alias doclf="docker logs -f"

# Remove commands
alias docrm="docker rm"
alias docrmi="docker rmi"

# Kill all running containers.
alias dockerkillall='docker kill $(docker ps -q)'

# Delete all stopped containers.
alias dockercleanc='printf "\n>>> Deleting stopped containers\n\n" && docker rm $(docker ps -a -q)'

# Delete all untagged images.
alias dockercleani='printf "\n>>> Deleting untagged images\n\n" && docker rmi $(docker images -q -f dangling=true)'

# Delete all stopped containers and untagged images.
alias dockerclean='dockercleanc || true && dockercleani'

# Delete all tangling volumes
alias dockervolclean='printf "\n>>> Deleting untagged volumes\n\n" && docker volume rm $(docker volume ls -qf dangling=true)'

# Delete all downloaded images
alias dockerimgclean='for image in $(docker images -q); do docker rmi $image; done'
