#!/usr/local/bin/zsh

# ZSHENV General
#
#

# History settings
export HISTFILESIZE=10000
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.zsh_history
export KEYTIMEOUT=1							# reduce vi-mode lag of 0.4 second delay to 0.1

# General exports
export PAGER="less"

# Preferred editor
export EDITOR="emacsclient"

# Use emacsclient from terminal
export VISUAL="emacsclient"

# Lang variables
export LC_CTYPE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"

# prevent emacs term-mode to print "4m" at the end of each command
export TERM=xterm-256color

# Add ~/bin to our PATH
[[ -d "$HOME/bin" ]] && export PATH=$PATH:$HOME/bin

# Add /opt/local/bin
[[ -d "/opt/local/bin" ]] && export PATH=$PATH:/opt/local/bin
