#!/usr/local/bin/zsh

# NODENV
#
#
if [ `uname -s` = "FreeBSD" ]; then
	# do nothing
elif [ `uname -s` = "Linux" ]; then
	export PATH="$HOME/.nodenv/bin:$PATH"
	eval "$(nodenv init -)"
	nodenv rehash
else
    if which nodenv > /dev/null; then
      eval "$(nodenv init -)"
	  nodenv rehash
    fi
fi

