#!/usr/local/bin/zsh

# JAVA
#
#

# 1.6 Apple Java
export JDK6="/System/Library/Frameworks/JavaVM.framework/Home"

# Oracle JDK 1.7 and higher
export JDK7="`ls /Library/Java/JavaVirtualMachines | grep 1.7 |  sort -n | tail -n 1`"
export JDK8="`ls /Library/Java/JavaVirtualMachines | grep 1.8 |  sort -n | tail -n 1`"

# Default JDK
export defaultJDK=$JDK8

if [ `uname -s` = "FreeBSD" ]; then
    # OpenJDK 7
    export JAVA_HOME="/usr/local/openjdk7"
else
    export JAVA_HOME="/Library/Java/JavaVirtualMachines/${defaultJDK}/Contents/Home"
fi

# Maven settings
# Using maven2? Then, use M2_HOME! If you have maven3, DO NOT USE M2_HOME!
#export M2_HOME="/usr/share/maven"
export MAVEN_OPTS="-Xmx3072m -XX:MaxPermSize=1024m -Xms128m -Djava.awt.headless=true"

function java-versions() {
	env | grep JDK
}

# Fix IntelliJ 12+ vmoptions when upgrading
# See more details here:
# http://stackoverflow.com/questions/13578062/how-to-increase-ide-memory-limit-in-intellij-idea-on-mac
# http://www.jetbrains.com/idea/webhelp/increasing-memory-heap.html
function fix-intellij-vmoptions() {
    mkdir -p ${HOME}/Library/Preferences/IntelliJIdea13
    echo "[Writing new configuration]"
    cat << EOF > $HOME/Library/Preferences/IntelliJIdea13/idea.vmoptions
-Xms512m
-Xmx3072m
-XX:MaxPermSize=1024m
#-XX:MaxGCPauseMillis=10
-XX:ReservedCodeCacheSize=96m
-XX:+UseCodeCacheFlushing
-XX:+UseCompressedOops
EOF
    echo ""
    echo "Following file was written:"
    echo "$HOME/Library/Preferences/IntelliJIdea13/idea.vmoptions"
    echo ""
    cat $HOME/Library/Preferences/IntelliJIdea13/idea.vmoptions
    echo ""
    echo "Done. Restart IntelliJ for changes to take effect."
    return 0
}
