#!/usr/local/bin/zsh

# HOMEBREW sbin
#
#

# Added for brew zsh-completions
if [[ `uname -s` == "Darwin" ]]; then
	unalias run-help
	autoload run-help
	HELPDIR=/usr/local/share/zsh/helpfiles

	export PATH=/usr/local/bin:/usr/local/sbin:$PATH

	[[ -d /usr/local/share/python ]] && export PATH=/usr/local/share/python:$PATH
	[[ -d /usr/local/share/npm/bin ]] && export PATH=/usr/local/share/npm/bin:$PATH
fi
