#!/usr/local/bin/zsh

# JAVA
#
#

# JDKs
if [[ "`uname -s`" == "FreeBSD" ]]; then
    export JDK7="/usr/local/openjdk7"
    export JDK8="/usr/local/openjdk8"
    defaultJDK=$JDK7
else
    export JDK6=`/usr/libexec/java_home -v 1.6`
    export JDK7=`/usr/libexec/java_home -v 1.7`
    export JDK8=`/usr/libexec/java_home -v 1.8`
    defaultJDK=$JDK8
fi
export JAVA_HOME="${defaultJDK}"

# Maven settings
# Using maven2? Then, use M2_HOME! If you have maven3, DO NOT USE M2_HOME!
function set-maven-opts() {
  #export M2_HOME="/usr/share/maven"
  if [[ "$JAVA_HOME" != "$JDK8" ]]; then
    MAVEN_EXTRA_OPTS="-XX:MaxPermSize=1024m"
  fi
  export MAVEN_OPTS="-Xmx3072m -Xms128m -Djava.awt.headless=true ${MAVEN_EXTRA_OPTS}"
}
set-maven-opts

function java-versions() {
	env | grep JDK
}

function switch-to-java() {
  jdk=$1

  if [[ "$jdk" == "1.7" ]]; then
    JAVA_HOME=$JDK7
  elif [[ "$jdk" == "7" ]]; then
    JAVA_HOME=$JDK7
  elif [[ "$jdk" == "1.8" ]]; then
    JAVA_HOME=$JDK8
  elif [[ "$jdk" == "8" ]]; then
    JAVA_HOME=$JDK8
  else
    JAVA_HOME=$JDK8
  fi

  export JAVA_HOME
  echo "Switching to $JAVA_HOME"
  set-maven-opts
  echo "Setting MAVEN_OPTS=$MAVEN_OPTS"
}

# Fix IntelliJ 12+ vmoptions when upgrading
# See more details here:
# http://stackoverflow.com/questions/13578062/how-to-increase-ide-memory-limit-in-intellij-idea-on-mac
# http://www.jetbrains.com/idea/webhelp/increasing-memory-heap.html
function fix-intellij-vmoptions() {
    mkdir -p ${HOME}/Library/Preferences/IntelliJIdea14
    echo "[Writing new configuration]"
    cat << EOF > $HOME/Library/Preferences/IntelliJIdea14/idea.vmoptions
-Xms512m
-Xmx3072m
-XX:MaxPermSize=1024m
-XX:ReservedCodeCacheSize=96m
-XX:+UseCodeCacheFlushing
-XX:+UseCompressedOops
EOF
    echo ""
    echo "Following file was written:"
    echo "$HOME/Library/Preferences/IntelliJIdea14/idea.vmoptions"
    echo ""
    cat $HOME/Library/Preferences/IntelliJIdea14/idea.vmoptions
    echo ""
    echo "Done. Restart IntelliJ for changes to take effect."
    return 0
}
