#!/usr/local/bin/zsh

# RBENV
#
#
if [ `uname -s` = "FreeBSD" ]; then
#elif [ `uname -s` = "Linux" ]; then
#	export PATH="$HOME/.pyenv/bin:$PATH"
#	eval "$(pyenv init -)"
#	pyenv rehash
else
    if which nodenv > /dev/null; then
      eval "$(nodenv init -)"
	  nodenv rehash
    fi
fi

