#!/usr/local/bin/zsh

if [[ -d "/usr/local/Cellar/go" ]]; then
    export GOROOT=/usr/local/Cellar/go/`ls /usr/local/Cellar/go`/libexec
    export PATH=$PATH:$GOROOT/bin
fi

if [[ -d "${HOME}/src/go" ]]; then
    export GOPATH="$HOME/src/go"
    export PATH=$PATH:$GOPATH/bin
fi
