#!/usr/local/bin/zsh

# ZSHENV PERL
#
#

export PATH="/Users/hgschmidt/perl5/bin${PATH:+:${PATH}}"
export PERL5LIB="/Users/hgschmidt/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"
export PERL_LOCAL_LIB_ROOT="/Users/hgschmidt/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"
export PERL_MB_OPT="--install_base \"/Users/hgschmidt/perl5\""
export PERL_MM_OPT="INSTALL_BASE=/Users/hgschmidt/perl5"
