#!/usr/local/bin/zsh

# Powerline ENV
#
#

if [[ -z `which pip` && -z `which pyenv` ]]; then
    # Generate ~/.powerline.conf
    export POWERLINE_TMUX_CONF="`pip show powerline-status | grep ^Location | awk '{print $2}'`/powerline/bindings/tmux/powerline.conf"
    ln -nsf $POWERLINE_TMUX_CONF ~/.powerline.conf
fi

# Run powerline-daemon
[[ -f `which powerline-daemon` ]] && powerline-daemon -q
