#!/usr/local/bin/zsh

# Init docker
#
#
if [[ "`uname -s`" == "Darwin" ]]; then
  export DOCKER_TLS_VERIFY="1"
  export DOCKER_HOST="tcp://192.168.99.100:2376"
  export DOCKER_CERT_PATH="/Users/hgschmidt/.docker/machine/machines/default"
  export DOCKER_MACHINE_NAME="default"
fi

# Kill all running containers.
alias dockerkillall='docker kill $(docker ps -q)'

# Delete all stopped containers.
alias dockercleanc='printf "\n>>> Deleting stopped containers\n\n" && docker rm $(docker ps -a -q)'

# Delete all untagged images.
alias dockercleani='printf "\n>>> Deleting untagged images\n\n" && docker rmi $(docker images -q -f dangling=true)'

# Delete all stopped containers and untagged images.
alias dockerclean='dockercleanc || true && dockercleani'

# Circumvent docker cert error
alias docker='docker --tlsverify=false'
