#!/usr/local/bin/zsh

# ZSHENV GIT
#
#

# Following is provided via hub (https://github.com/github/hub) and
# wraps git automatically.
eval "$(hub alias -s)"

# Aliases
alias gpr="git pull --rebase -v"
alias grpo="git remote prune origin"
alias git-last-authors='for branch in $(git branch -r | grep -v HEAD);do echo -e $(git show --format="%ai %ar by %an" $branch | head -n 1) \\t$branch; done | sort -r'
