#!/usr/local/bin/zsh

# RBENV
#
#
if [ `uname -s` = "FreeBSD" ]; then
    export PYENV_ROOT="${HOME}/.pyenv"
    if [ -d "${PYENV_ROOT}" ]; then
        export PATH="${PYENV_ROOT}/bin:${PATH}"
        eval "$(pyenv init -)"
    fi
elif [ `uname -s` = "Linux" ]; then
	export PATH="$HOME/.pyenv/bin:$PATH"
	eval "$(pyenv init -)"
	pyenv rehash
else
	export PYENV_ROOT=/usr/local/opt/pyenv
	if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
	pyenv rehash
fi
