#!/usr/local/bin/zsh

# NODENV
#
#
if [[ `uname -s` = "FreeBSD" ]]; then
	# do nothing
elif [[ `uname -s` = "Linux" ]]; then
	export PATH="$HOME/.nodenv/bin:$PATH"
	eval "$(nodenv init -)"
	nodenv rehash
else
  export PATH="node_modules/.bin:$PATH"

  if which nodenv > /dev/null; then
    eval "$(nodenv init -)"
    nodenv rehash
  fi
fi

# NVM
#
#
if [[ -f '/usr/local/opt/nvm/nvm.sh' ]]; then
	export NVM_DIR="$HOME/.nvm"
	. "/usr/local/opt/nvm/nvm.sh"
  #[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
fi
