#!/usr/local/bin/zsh

# Use gpg-agent as SSH agent (for smart keys)
#
#
ps x | grep -v "grep" | grep "gpg-agent.*--enable-ssh-support" > /dev/null
gpg_agent_ssh_enabled=$?
if [[ $gpg_agent_ssh_enabled -eq 1 ]];then
  echo "Stopping running gpg-agent with default parameters ..."
	gpgconf --kill gpg-agent

  echo "Starting gpg-agent with enabled SSH support ..."
	gpg-agent --daemon --enable-ssh-support
fi

export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
launchctl setenv SSH_AUTH_SOCK $(gpgconf --list-dirs agent-ssh-socket)

GPG_TTY=$(tty)
export GPG_TTY
