#!/bin/zsh

function pj() {
  ps aux | grep "$JAVA_HOME" | grep -v "grep" | awk '{print $2, $11, $(NF)}'
}

function pjk() {
  for pid in `pj | awk '{print $1}'`
  do
    echo ">>> Killing [$pid]"
    kill -9 $pid
  done
}

function pjgk() {
  for pid in `pj | grep "com.meltwater.ids" | awk '{print $1}'`
  do
    echo ">>> Killing [$pid]"
    kill -9 $pid
  done
}

alias h=history
alias sl=ls
alias sshconfig='vim ~/.ssh/config'
alias p=python2
alias p2=python2
alias p3=python3
alias venv=virtualenv-2.7
alias venv2=virtualenv-2.7
alias venv3=virtualenv-3.3
alias pep8='pep8 --max-line-length=120'
alias cdv=cdvirtualenv
#alias listwifi=sudo /sbin/ifconfig -v wlan0 list scan | awk '{print $4, $5, "\t\t", $1}'
alias vi=vim
