#!/bin/zsh

alias h=history
alias sl=ls
alias vi=vim
alias e="emacsclient -t"
alias ec="emacsclient -c"
alias be="bundle exec"
alias ber="bundle exec rake"
alias buo="brew update && brew outdated"
alias buc="brew upgrade && brew cleanup"
alias buuc="brew update && brew upgrade && brew cleanup"
alias rma-list-queues="rabbitmqadmin list queues vhost name messages messages_ready messages_unacknowledged"
alias rma-list-exchanges="rabbitmqadmin list exchanges vhost name type"
