#!/usr/local/bin/zsh

# ZSH
#
#
fpath=($fpath $HOME/.zsh/functions)
fpath=(/usr/local/share/zsh-completions $fpath)
typeset -U fpath

# SOURCE ALL ENVIRONMENT CONFIGS
#
#
for config in ${HOME}/.zsh/env-enabled/*
do
    . ${config}
done

export PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=":" '!a[$1]++')
