#!/bin/zsh

# HOMEBREW sbin
#
#
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

if [[ -d /usr/local/share/python ]]; then
    PATH=/usr/local/share/python:$PATH
    export PATH
fi

if [[ -d /usr/local/share/npm/bin ]]; then
    PATH=/usr/local/share/npm/bin:$PATH
    export PATH
fi
