#!/usr/local/bin/zsh

# ZSH
#
#
fpath=($fpath $HOME/.zsh/functions)
fpath=(/usr/local/share/zsh-completions $fpath)
typeset -U fpath

# GENERAL ENV
#
#
export LC_CTYPE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"

# $HOME/bin
#
# Add ~/bin to our PATH
if [[ -d "${HOME}/bin" ]]; then
	export PATH=$PATH:$HOME/bin
fi

# Add /opt/local/bin
if [[ -d "/opt/local/bin" ]]; then
    export PATH=$PATH:/opt/local/bin
fi

# SOURCE ALL ENVIRONMENT CONFIGS
#
#
for config in ${HOME}/.zsh/env-enabled/*
do
    . ${config}
done


