# zgitinit and prompt_otype_setup must be somewhere in your $fpath, see README for more.

# Some ZSH options
setopt promptsubst
setopt CORRECT					# command CORRECTION
setopt EXTENDED_HISTORY		# puts timestamps in history
setopt HASH_CMDS
bindkey "^R" history-incremental-search-backward
bindkey "^S" history-incremental-search-forward
stty stop undef

# Added for brew zsh-completions
if [ `uname -s` != "Linux" ]; then
	unalias run-help
	autoload run-help
	HELPDIR=/usr/local/share/zsh/helpfiles
fi

# General exports
export PAGER="less"
export EDITOR="vim"
export BZR_EDITOR="vim"

# Source aliases files
if [[ -f $HOME/.zsh/zsh-aliases ]]; then
	. $HOME/.zsh/zsh-aliases
fi

# Source zshenv files
if [[ -f $HOME/.zsh/zshenv ]]; then
	. $HOME/.zsh/zshenv
fi

# Load the prompt theme system
autoload -U promptinit
autoload -U compinit; compinit
promptinit

# Use the otype prompt theme
prompt otype
