# zgitinit and prompt_otype_setup must be somewhere in your $fpath, see README for more.

# ZSH options
. ${HOME}/.zsh/zsh-options

# Source aliases files
. $HOME/.zsh/zsh-aliases

# Source zshenv files
. $HOME/.zsh/zshenv

# Load the prompt theme system
autoload -U promptinit
autoload -U compinit; compinit
promptinit

# Use the otype prompt theme
prompt otype
